apiVersion : apps/v1
kind: Deployment
metadata:
  name: bbadshoppingtest 
spec:
  replicas: 1
  selector:
  matchLabels:
  app: bbadshoppingtest
  template:
    metadata:
      labels:
        app: bbadshoppingtest 
    spec:
      containers:
        - name: bbadshoppingtest 
          image: testdevopstest.azurecr.io/bbadshoppingtest
          ports:
          - containerPort: 80
